server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          # --- CONFIGURACIÃ“N DE CORS ---
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://localhost:8080"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - Content-Disposition
                  - Content-Type
                  - Content-Length
                  - Authorization
                allowCredentials: true
                maxAge: 3600
          # --- FIN DE CORS ---

          # Las rutas van dentro de server.webflux
          routes:
            - id: boutique-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/**

            - id: openapi-docs
              uri: http://localhost:8081
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - name: RewritePath
                  args:
                    regexp: "/v3/api-docs(?<segment>/?.*)"
                    replacement: "/v3/api-docs${segment}"

            - id: swagger-ui
              uri: http://localhost:8081
              predicates:
                - Path=/swagger/**
              filters:
                - name: RewritePath
                  args:
                    regexp: "/swagger(?<segment>/?.*)"
                    replacement: "/swagger-ui${segment}"

            - id: ai-service
              uri: http://localhost:8000
              predicates:
                - Path=/ia/**

jwt:
  secret: "%<Ag|5%fylZQoKK>cLS2tz{G26i.HT3W8m4-_TraiUD"